Resources:
  Products:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "ProductId"
          AttributeType: "S"
        - AttributeName: "ProductName"
          AttributeType: "S"
        - AttributeName: "ProductType"
          AttributeType: "S"
        - AttributeName: "Price"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "ProductId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
    Type: AWS::Lambda::Function
    Properties:
      Runtime: nodejs12.x
      Role: arn:aws:iam::303669817364:role/AWSRoleForLambda
      Handler: index.handler
      FunctionName: Products
      Timeout: 30
      MemorySize: 128
      Code:
        ZipFile: | 
          exports.handler =  async function(event, context) {
            console.log("EVENT: \n" + JSON.stringify(event, null, 2))
            return context.logStreamName
          }
      Description: Function to perform CRUD for Products.

